DELETE https://crudcrud.com/api/dc5201f0cf314b16b81218f86a523e2b/unicorn/66efc448fe837603e816cb0f


###
GET https://crudcrud.com/api/dc5201f0cf314b16b81218f86a523e2b/unicorn/66efc448fe837603e816cb0f

###
POST https://crudcrud.com/api/dc5201f0cf314b16b81218f86a523e2b/unicorn
Content-Type: application/json

{
  "name": "Unic",
  "color": "red"
}

###

PUT https://crudcrud.com/api/dc5201f0cf314b16b81218f86a523e2b/unicorn/66efc448fe837603e816cb0f
Content-Type: application/json

{
  "name": "Unic",
  "color": "yellow"
}